# -*- coding: utf-8 -*-
"""ML_Decision_Tree_Training_and_Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E33x49uWxTGzl9IP17RUH5_sZN6tkaMy
"""

from google.colab import files

uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

df = pd.read_csv("MLSSHMERPS_Data_Samples.csv")

df.head()

print(df.shape)

print(df.columns)

print(df['Label'].value_counts())

X = df[['BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)']]

y = df['Label']

le = LabelEncoder()

y = le.fit_transform(y)

from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Create Decision Tree model
cv_model = DecisionTreeClassifier(random_state=42)

# Stratified 5-Fold Cross Validation
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cv_scores = cross_val_score(
    cv_model,
    X,
    y,
    cv=cv,
    scoring='accuracy'
)

print("Stratified 5-Fold Cross Validation Accuracy for each fold:")
print(cv_scores)
print("\nMean Cross Validation Accuracy:", np.mean(cv_scores))
print("Standard Deviation:", np.std(cv_scores))

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import label_binarize

# Predicted probabilities
y_prob = model.predict_proba(X_test)

# Binarize true labels
classes = np.unique(y)
y_test_bin = label_binarize(y_test, classes=classes)

# Multi-class ROC-AUC (One-vs-Rest)
roc_auc = roc_auc_score(
    y_test_bin,
    y_prob,
    multi_class='ovr',
    average='macro'
)

print("ROC-AUC Score:", roc_auc)

from sklearn.metrics import matthews_corrcoef

mcc = matthews_corrcoef(y_test, y_pred)

print("Matthews Correlation Coefficient (MCC):", mcc)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

import pickle

pickle.dump(model, open("soldier_model.pkl", "wb"))

from google.colab import files

files.download("soldier_model.pkl")

prediction = model.predict([[145, 91.8, 47.2, 28.5, 2200, 3500, 16500]])

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[185, 91.8, 47.2, 28.5, 2200, 3500, 16500]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[185, 89.8, 47.2, 28.5, 2200, 3500, 16500]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[175, 89.8, -12.2, 28.5, 2200, 3500, 16500]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[80, 99.0, 30.0, 45.0, 1400, -200, 16000]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[120, 95.0, 38.0, 50.0, 1800, 600, 16000]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[145, 90.0, -8.0, 70.0, 1800, 1200, 16000]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_estimator(
    model,
    X_test,
    y_test
)

plt.title("Decision Tree Confusion Matrix")
plt.show()

from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))

tree.plot_tree(
    model,
    filled=True,
    fontsize=8
)

plt.show()

import pandas as pd

sample = pd.DataFrame(
    [[142, 94.0, 38.0, 50.0, 1730, -153, 20620]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[179, 94.0, -18.0, 50.0, 1730, -153, 20620]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pandas as pd

sample = pd.DataFrame(
    [[179, 94.0, 0.0, 50.0, 1730, -153, 20620]],
    columns=[
        'BPM',
        'SpO2',
        'Temp',
        'Humidity',
        'Motion(AX)',
        'Motion(AY)',
        'Motion(AZ)'
    ]
)

prediction = model.predict(sample)

print(le.inverse_transform(prediction))

import pickle

# Save trained Decision Tree model
with open("soldier_model.pkl", "wb") as f:
    pickle.dump(model, f)

# Save Label Encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("Files saved successfully!")

import os

print(os.listdir())

from google.colab import files

files.download("soldier_model.pkl")

from google.colab import files

files.download("label_encoder.pkl")

print(type(model))
print(type(le))